export { useRelationalStore, skipJsonStoresWrite } from "./relationalConfig.js";
export { exportJsonBackup } from "./jsonExport.js";
export {
  loadParceirosFromSql,
  loadVinculosFromSql,
  saveParceirosToSql,
  upsertParceiroRowToSql,
  deleteParceiroRowFromSql,
  saveVinculosToSql,
  loadVeiculosFromSql,
  saveVeiculosToSql,
  loadClientesFromSql,
  loadClientesByIdsFromSql,
  queryClientesFromSql,
  resolveClienteIdFromSql,
  resolveVeiculoIdFromSql,
  queryVeiculosFromSql,
  queryVeiculosByIdsFromSql,
  type ClientesSqlFilter,
  type VeiculosSqlFilter,
  saveClientesToSql,
  type ParceirosDbShape,
  type VinculosDbShape,
  type VeiculosDbShape,
  type ClientesDbShape,
} from "./coreRepositories.js";
export {
  loadContratosFromSql,
  saveContratosToSql,
  queryContratosFromSql,
  type ContratosSqlFilter,
  loadLocacoesFromSql,
  saveLocacoesToSql,
  queryLocacoesFromSql,
  type LocacoesSqlFilter,
  loadInfracoesFromSql,
  saveInfracoesToSql,
  queryInfracoesFromSql,
  type InfracoesSqlFilter,
  loadClienteDespesasFromSql,
  queryClienteDespesasFromSql,
  queryClienteDespesaByReferenciaFromSql,
  upsertClienteDespesaRowToSql,
  saveClienteDespesasToSql,
  type ClienteDespesasSqlFilter,
  loadParceiroDespesasFromSql,
  saveParceiroDespesasToSql,
  queryParceiroDespesasFromSql,
  type ParceiroDespesasSqlFilter,
  loadTriagensFromSql,
  saveTriagensToSql,
  loadClienteAnaliseFromSql,
  saveClienteAnaliseToSql,
  type TriagemDbShape,
  type ClienteAnaliseDbShape,
} from "./domainRepositories.js";
