export { queryResumoCountsFromSql, type ResumoCounts } from "./resumoCounts.js";
export { useRelationalStore, assertRelationalStore, skipJsonStoresWrite } from "./relationalConfig.js";
export { exportJsonBackup } from "./jsonExport.js";
export {
  loadParceirosFromSql,
  loadVinculosFromSql,
  saveParceirosToSql,
  upsertParceiroRowToSql,
  deleteParceiroRowFromSql,
  saveVinculosToSql,
  upsertVinculoToSql,
  deleteVinculoFromSql,
  deleteVinculosByVeiculoFromSql,
  loadVeiculosFromSql,
  loadVeiculosFromSqlLight,
  saveVeiculosToSql,
  upsertVeiculoToSql,
  loadClientesFromSql,
  loadClientesByIdsFromSql,
  queryClientesFromSql,
  resolveClienteIdFromSql,
  resolveVeiculoIdFromSql,
  queryVeiculosFromSql,
  queryVeiculosByIdsFromSql,
  type ClientesSqlFilter,
  type VeiculosSqlFilter,
  saveClientesToSql,
  upsertClienteToSql,
  type ParceirosDbShape,
  type VinculosDbShape,
  type VeiculosDbShape,
  type ClientesDbShape,
} from "./coreRepositories.js";
export {
  loadContratosFromSql,
  saveContratosToSql,
  upsertContratoToSql,
  deleteContratoFromSql,
  queryContratosFromSql,
  hasContratoAssinadoColumns,
  type ContratosSqlFilter,
  loadLocacoesFromSql,
  saveLocacoesToSql,
  upsertLocacaoToSql,
  deleteLocacaoFromSql,
  queryLocacoesFromSql,
  type LocacoesSqlFilter,
  loadInfracoesFromSql,
  saveInfracoesToSql,
  upsertInfracaoToSql,
  queryInfracoesFromSql,
  type InfracoesSqlFilter,
  loadClienteDespesasFromSql,
  queryClienteDespesasFromSql,
  queryClienteDespesaByReferenciaFromSql,
  upsertClienteDespesaRowToSql,
  updateClienteDespesaRowToSql,
  insertClienteDespesaRowToSql,
  saveClienteDespesasToSql,
  type ClienteDespesasSqlFilter,
  type PersistClienteDespesaSqlOpts,
  loadParceiroDespesasFromSql,
  saveParceiroDespesasToSql,
  upsertParceiroDespesaToSql,
  deleteParceiroDespesaFromSql,
  deleteParceiroDespesaByOrigemFromSql,
  queryParceiroDespesasFromSql,
  type ParceiroDespesasSqlFilter,
  loadTriagensFromSql,
  saveTriagensToSql,
  upsertTriagemToSql,
  loadClienteAnaliseFromSql,
  saveClienteAnaliseToSql,
  upsertClienteAnaliseRowToSql,
  type TriagemDbShape,
  type ClienteAnaliseDbShape,
} from "./domainRepositories.js";
export {
  queryVendasFromSql,
  obterVendaFromSql,
  upsertVendaToSql,
  deleteVendaFromSql,
  type VendasSqlFilter,
} from "./vendasRepositories.js";
